function(clang_format input_files)
    find_program(CLANG_FORMAT NAMES "clang-format" "clang-format-3.6")
    if(CLANG_FORMAT)
        message(STATUS "Found clang-format at ${CLANG_FORMAT}")
        execute_process(${CLANG_FORMAT} -i -style=Google -fallback-style=none ${input_files})
    else()
        message(WARNING "Unable to find clang-format executable, will skip formatting enforcement.")
    endif()
endfunction()